### ISSUE TITLE
Panic during merges

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#172]
When merging values, if we have an array, with a map object, whose `name` key is not a string, we get a panic:

```
array-of-maps:
- name: { subkey1, subkey2: val2 }
```

results in:

```
panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
panic(0x462720, 0xc8200f6ab0)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/geofffranks/spruce.(*Merger).mergeArrayByKey(0xc8200dbd70, 0x743ab0, 0x0, 0x0, 0xc8200f6a80, 0x1, 0x1, 0xc8200117a0, 0xf, 0x4eac38, ...)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:334 +0x31c
github.com/geofffranks/spruce.(*Merger).mergeArrayDefault(0xc8200dbd70, 0x743ab0, 0x0, 0x0, 0xc8200f6a80, 0x1, 0x1, 0xc8200117a0, 0xf, 0x0, ...)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:287 +0x303
github.com/geofffranks/spruce.(*Merger).mergeArray(0xc8200dbd70, 0x743ab0, 0x0, 0x0, 0xc8200117c0, 0x1, 0x1, 0xc8200117a0, 0xf, 0x0, ...)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:201 +0x143d
github.com/geofffranks/spruce.(*Merger).mergeObj(0xc8200dbd70, 0x0, 0x0, 0x39e800, 0xc8200cae20, 0xc8200117a0, 0xf, 0x0, 0x0)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:143 +0x7fb
github.com/geofffranks/spruce.(*Merger).mergeMap(0xc8200dbd70, 0xc82000bb30, 0xc82000bc50, 0x4e7058, 0x1)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:95 +0x880
github.com/geofffranks/spruce.(*Merger).Merge(0xc8200dbd70, 0xc82000bb30, 0xc82000bc50, 0x0, 0x0)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:78 +0x5a
main.mergeAllDocs(0xc82000bb30, 0xc820011500, 0x1, 0x1, 0x0, 0x0)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/cmd/spruce/main.go:194 +0x6bf
main.main()
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/cmd/spruce/main.go:96 +0x9cf
```

This also occurs in situations where you override the merge-key, like this:

```
array-of-maps:
- (( merge on mergekey ))
- mergekey: { subkey1, subkey2: val2 }
```

**Comment by thomasmmitchell** [comment]
This is the trace for the custom merge key case:
```
→  spruce merge sprtest.yml
panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
panic(0x46c8e0, 0xc820011e30)
	/goroot/src/runtime/panic.go:481 +0x3e6
github.com/geofffranks/spruce.(*Merger).mergeArrayByKey(0xc8200ddd70, 0x754980, 0x0, 0x0, 0xc8200cafb0, 0x1, 0x1, 0xc820011790, 0xf, 0xc8200cad2c, ...)
	/tmp/build/01f561ac/gopath/src/github.com/geofffranks/spruce/merge.go:334 +0x31c
github.com/geofffranks/spruce.(*Merger).mergeArray(0xc8200ddd70, 0x754980, 0x0, 0x0, 0xc8200cafa0, 0x2, 0x2, 0xc820011790, 0xf, 0x0, ...)
	/tmp/build/01f561ac/gopath/src/github.com/geofffranks/spruce/merge.go:183 +0xf79
github.com/geofffranks/spruce.(*Merger).mergeObj(0xc8200ddd70, 0x0, 0x0, 0x3a6300, 0xc8200cafc0, 0xc820011790, 0xf, 0x0, 0x0)
	/tmp/build/01f561ac/gopath/src/github.com/geofffranks/spruce/merge.go:143 +0x7fb
github.com/geofffranks/spruce.(*Merger).mergeMap(0xc8200ddd70, 0xc82000bb60, 0xc82000bc80, 0x4f3f80, 0x1)
	/tmp/build/01f561ac/gopath/src/github.com/geofffranks/spruce/merge.go:95 +0x880
github.com/geofffranks/spruce.(*Merger).Merge(0xc8200ddd70, 0xc82000bb60, 0xc82000bc80, 0x0, 0x0)
	/tmp/build/01f561ac/gopath/src/github.com/geofffranks/spruce/merge.go:78 +0x5a
main.mergeAllDocs(0xc82000bb60, 0xc8200114d0, 0x1, 0x1, 0x0, 0x0)
	/tmp/build/01f561ac/gopath/src/github.com/geofffranks/spruce/cmd/spruce/main.go:194 +0x6bf
main.main()
	/tmp/build/01f561ac/gopath/src/github.com/geofffranks/spruce/cmd/spruce/main.go:96 +0x9cf
```

**Comment by thomasmmitchell** [comment]
Also, there is no panic if the merge key is an int. Its more accurate to say that the merge key cannot be a data structure.

**Comment by thomasmmitchell** [comment]
I see the problem in the code. Only question is whether or not you want it to be semantically correct to merge on a data structure match, or for it to throw a more sanctioned error.

**Comment by geofffranks** [comment]
I think i'm fine with it just refusing to do a key-based-merge if the values of the keys are not strings, and either falling through to the next merge strategy, or erroring, as applicable for default vs explicit merging

**Comment by thomasmmitchell** [comment]
If thats the strategy, then I would say definitely error if the user explicitly said to merge on that key... and if it was due to defaults... I don't know. Something about adding more random magic to the default merge behavior makes me sad.

**Comment by geofffranks** [comment]
Ok. go with the tentative  suggestion for erroring with a message telling you how to override if really desired. This seems like too much of a wackadoo edge case where not erroring will waste a lot of time trying to discover what went wrong
