### ISSUE TITLE
Crash when running first example

### ISSUE THREAD

**Issue by Jonty** [geofffranks/spruce#65]
When running the first example current spruce master crashes. It does not crash when running v0.12.0.

````
jonty@towel:~/code/go/src/github.com/geofffranks/spruce (master)$ git rev-parse HEAD
293a7e78d6e370731706ceb951320a468d34b810
````
````
jonty@towel:~/code/go/src/github.com/geofffranks/spruce (master)$ spruce merge assets/examples/example.yml assets/examples/example2.yml
panic: interface conversion: interface is int, not string

goroutine 1 [running]:
main.(*Evaluator).DataFlow.func2(0x20b4a0, 0xc82006b290)
	/Users/jonty/code/go/src/github.com/geofffranks/spruce/evaluator.go:61 +0x5b4
main.(*Evaluator).DataFlow.func1(0x20b4a0, 0xc82006b290)
	/Users/jonty/code/go/src/github.com/geofffranks/spruce/evaluator.go:53 +0xa49
main.(*Evaluator).DataFlow.func2(0x20b4a0, 0xc82006af60)
	/Users/jonty/code/go/src/github.com/geofffranks/spruce/evaluator.go:62 +0x64b
main.(*Evaluator).DataFlow(0xc82008de00, 0x0, 0x0)
	/Users/jonty/code/go/src/github.com/geofffranks/spruce/evaluator.go:75 +0x258
main.(*Evaluator).Run(0xc82008de00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jonty/code/go/src/github.com/geofffranks/spruce/evaluator.go:376 +0xbf
main.main()
	/Users/jonty/code/go/src/github.com/geofffranks/spruce/main.go:133 +0x634

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
````

**Comment by filefrog** [comment]
Looks like it's time to integrate examples into the test suite :grin:
